on:
  push:
    branches: [ master ]
    paths:
    - ./azure
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

permissions:
  id-token: write

name: WITSML-SERVER-AZURE-INFRA
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_SP_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_SP_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create resource group
      run: |
        az group create --name ${{ secrets.AZURE_WITSML_RESOURCE_GROUP_DEV }} --location ${{ secrets.AZURE_WITSML_RESOURCE_GROUP_LOCATION_DEV }}
        az group show --name ${{ secrets.AZURE_WITSML_RESOURCE_GROUP_DEV }}    

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_WITSML_RESOURCE_GROUP_DEV }}
        template: ./azure/main.bicep
