on:
  push:
    branches: [ master ]
    paths:
    - ./src
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

permissions:
  id-token: write

name: WITSML-SERVER-BUILD
jobs:
  build:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
      with:
        submodules: 'true'

    - run: 'git submodule update --init --recursive'

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_SP_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_SP_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup nuget
      uses: nuget/setup-nuget@v1

    - run: nuget restore src\PDS.WITSMLstudio.sln

    - name: Build solution
      run: |
        msbuild src\PDS.WITSMLstudio.sln -t:rebuild -restore -property:Configuration=Release

    - name: Publish web server
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_WITS_SERVER_DEV_NAME }}
        publish-profile: ${{ secrets.AZURE_APP_WITS_SERVER_DEV_PUBLISH_PROFILE }}
        package: src\store
